'use client'

// ─────────────────────────────────────────────────────────────────────────────
// Master Control Panel — user detail (read-only).
// Reads /api/admin/users/[userId]/detail (super-admin gated) and renders
// three sections: Profile, Login Activity, Reports Generated by This User.
// No writes here — user mutations come later.
// ─────────────────────────────────────────────────────────────────────────────

import type { CSSProperties } from 'react'
import { useEffect, useState } from 'react'
import Link from 'next/link'
import { useParams, useRouter } from 'next/navigation'
import {
  Loader2, ArrowLeft, ShieldCheck, User as UserIcon, LogIn, FileText,
  ExternalLink, CheckCircle2, Circle,
} from 'lucide-react'
import { supabase } from '@/lib/supabase/client'
import type { AdminUserDetailResponse } from '@/app/api/admin/users/[userId]/detail/route'

// ── Design tokens (match /admin/control) ────────────────────────────────────
const NAVY = '#0A1628'
const PANEL = '#0F2140'
const BORDER = 'rgba(255,255,255,0.1)'
const ORANGE = '#E8520A'

const card: CSSProperties = { backgroundColor: PANEL, border: `1px solid ${BORDER}`, borderRadius: 10, padding: 20 }

// ── Helpers ─────────────────────────────────────────────────────────────────
function formatRole(role: string): string {
  return role.split('_').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ')
}

function displayName(u: { first_name: string | null; last_name: string | null; email: string }): string {
  const combined = [u.first_name, u.last_name].filter(Boolean).join(' ').trim()
  return combined.length > 0 ? combined : u.email
}

function orgStatusColor(status: string | null): { bg: string; fg: string } {
  switch (status) {
    case 'active':    return { bg: 'rgba(34,197,94,0.15)', fg: '#86EFAC' }
    case 'trial':     return { bg: 'rgba(14,165,233,0.15)', fg: '#7DD3FC' }
    case 'suspended': return { bg: 'rgba(239,68,68,0.15)', fg: '#FCA5A5' }
    case 'churned':   return { bg: 'rgba(255,255,255,0.08)', fg: 'rgba(255,255,255,0.5)' }
    default:          return { bg: 'rgba(255,255,255,0.08)', fg: 'rgba(255,255,255,0.6)' }
  }
}

function timeAgo(iso: string | null): string {
  if (!iso) return 'Never'
  const diff = Date.now() - new Date(iso).getTime()
  const d = Math.floor(diff / 86_400_000)
  if (d > 0) return `${d}d ago`
  const h = Math.floor(diff / 3_600_000)
  if (h > 0) return `${h}h ago`
  const m = Math.floor(diff / 60_000)
  return m > 0 ? `${m}m ago` : 'Just now'
}

function fmtDate(iso: string | null): string {
  if (!iso) return ''
  return new Date(iso).toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' })
}

function fmtDateTime(iso: string): string {
  return new Date(iso).toLocaleString('en-US', { year: 'numeric', month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' })
}

function reportTypeLabel(t: string): string {
  if (t === 'engagement_plan') return 'Engagement Plan'
  if (t === 'future_state') return 'Future State Plan'
  if (t === 'icp_calibration') return 'ICP Calibration Report'
  if (t === 'dcp_map') return 'DCP Map'
  if (t === 'insights') return 'Insights Report'
  return t
}

// ─────────────────────────────────────────────────────────────────────────────
// Page
// ─────────────────────────────────────────────────────────────────────────────
export default function UserDetailPage() {
  const router = useRouter()
  const params = useParams<{ userId: string }>()
  const userId = String(params?.userId ?? '')

  const [authChecking, setAuthChecking] = useState(true)
  const [loading, setLoading] = useState(true)
  const [data, setData] = useState<AdminUserDetailResponse | null>(null)
  const [error, setError] = useState<string | null>(null)

  // Same super-admin guard as /admin/control.
  useEffect(() => {
    async function check() {
      try {
        const { data: { user } } = await supabase.auth.getUser()
        if (!user) { router.replace('/auth/login'); return }
        const { data: row } = await supabase.from('users').select('is_super_admin').eq('id', user.id).maybeSingle()
        if (!row || !(row as { is_super_admin?: boolean }).is_super_admin) { router.replace('/dashboard'); return }
        setAuthChecking(false)
      } catch { router.replace('/dashboard') }
    }
    void check()
  }, [router])

  useEffect(() => {
    if (authChecking) return
    async function load() {
      if (!userId) return
      setLoading(true); setError(null)
      try {
        const res = await fetch(`/api/admin/users/${userId}/detail`)
        if (res.status === 404) {
          setData(null); setError('not_found'); return
        }
        if (!res.ok) throw new Error((await res.json().catch(() => ({}))).error || 'Failed to load user')
        const body = (await res.json()) as AdminUserDetailResponse
        setData(body)
      } catch (e) { setError(e instanceof Error ? e.message : 'Failed to load user') }
      finally { setLoading(false) }
    }
    void load()
  }, [authChecking, userId])

  if (authChecking) {
    return (
      <div style={{ backgroundColor: NAVY, minHeight: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
        <Loader2 size={28} className="animate-spin" style={{ color: 'rgba(255,255,255,0.4)' }} />
      </div>
    )
  }

  return (
    <div style={{ backgroundColor: NAVY, minHeight: '100vh', color: '#fff' }}>
      <div style={{ maxWidth: 1080, margin: '0 auto', padding: '24px 32px 48px' }}>
        <Link href="/admin/control" style={{ color: '#93C5FD', fontSize: 13, textDecoration: 'none', display: 'inline-flex', alignItems: 'center', gap: 6 }}>
          <ArrowLeft size={14} /> Back to Master Control Panel
        </Link>

        {loading ? (
          <div style={{ padding: 80, display: 'flex', justifyContent: 'center' }}>
            <Loader2 size={26} className="animate-spin" style={{ color: 'rgba(255,255,255,0.4)' }} />
          </div>
        ) : error === 'not_found' ? (
          <NotFound userId={userId} />
        ) : error ? (
          <div style={{ ...card, marginTop: 20, borderLeft: `3px solid #EF4444` }}>
            <p style={{ color: '#FCA5A5', margin: 0 }}>{error}</p>
          </div>
        ) : data ? (
          <UserDetail data={data} />
        ) : null}
      </div>
    </div>
  )
}

function NotFound({ userId }: { userId: string }) {
  return (
    <div style={{ ...card, marginTop: 20, borderLeft: `3px solid #FDBA74` }}>
      <h2 style={{ fontSize: 18, fontWeight: 700, margin: '0 0 8px' }}>User not found</h2>
      <p style={{ color: 'rgba(255,255,255,0.6)', fontSize: 13.5, margin: 0 }}>
        No user exists for id <code style={{ background: 'rgba(255,255,255,0.06)', padding: '2px 6px', borderRadius: 4 }}>{userId}</code>.
      </p>
    </div>
  )
}

// ─────────────────────────────────────────────────────────────────────────────
// Detail body
// ─────────────────────────────────────────────────────────────────────────────
function UserDetail({ data }: { data: AdminUserDetailResponse }) {
  const { user, org, login_activity, reports_generated } = data
  const name = displayName(user)
  const oc = orgStatusColor(org.status)

  return (
    <div>
      {/* Header */}
      <div style={{ marginTop: 14, marginBottom: 24 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 12, flexWrap: 'wrap' }}>
          <UserIcon size={22} style={{ color: ORANGE }} />
          <h1 style={{ fontSize: 24, fontWeight: 700, margin: 0 }}>{name}</h1>
          {user.is_super_admin && (
            <span style={{ backgroundColor: 'rgba(232,82,10,0.18)', color: '#FDBA74', border: '1px solid rgba(232,82,10,0.35)', borderRadius: 999, padding: '3px 12px', fontSize: 11, fontWeight: 700 }}>
              <ShieldCheck size={11} style={{ verticalAlign: 'middle', marginRight: 4 }} /> Super Admin
            </span>
          )}
          {user.is_active
            ? <span style={{ backgroundColor: 'rgba(34,197,94,0.15)', color: '#86EFAC', borderRadius: 999, padding: '3px 12px', fontSize: 11, fontWeight: 700 }}>Active</span>
            : <span style={{ backgroundColor: 'rgba(255,255,255,0.08)', color: 'rgba(255,255,255,0.55)', borderRadius: 999, padding: '3px 12px', fontSize: 11, fontWeight: 700 }}>Inactive</span>}
        </div>
        <p style={{ color: 'rgba(255,255,255,0.5)', fontSize: 13, margin: '6px 0 0' }}>
          {user.email} · {formatRole(user.role)}
        </p>
      </div>

      {/* 1. Profile */}
      <SectionCard title="Profile" icon={<UserIcon size={16} style={{ color: '#7DD3FC' }} />}>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, minmax(0,1fr))', gap: 12 }}>
          <ProfileField label="Name">{name}</ProfileField>
          <ProfileField label="Email">{user.email}</ProfileField>
          <ProfileField label="Role">{formatRole(user.role)}</ProfileField>
          <ProfileField label="Status">{user.is_active ? 'Active' : 'Inactive'}</ProfileField>
          <ProfileField label="Super admin">{user.is_super_admin ? 'Yes' : 'No'}</ProfileField>
          <ProfileField label="Joined">{fmtDate(user.created_at)}</ProfileField>
        </div>
        <div style={{ marginTop: 16, padding: 12, backgroundColor: 'rgba(255,255,255,0.02)', border: `1px solid ${BORDER}`, borderRadius: 8, display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 8, flexWrap: 'wrap' }}>
          <div>
            <div style={{ fontSize: 11, textTransform: 'uppercase', letterSpacing: '0.06em', color: 'rgba(255,255,255,0.5)', fontWeight: 700 }}>Account</div>
            <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginTop: 6 }}>
              <span style={{ fontSize: 14, fontWeight: 700 }}>{org.name}</span>
              <span style={{ backgroundColor: oc.bg, color: oc.fg, borderRadius: 999, padding: '2px 10px', fontSize: 11, fontWeight: 700, textTransform: 'capitalize' }}>
                {org.status ?? '—'}
              </span>
            </div>
            <div style={{ fontSize: 11.5, color: 'rgba(255,255,255,0.5)', marginTop: 4 }}>
              {org.industry ? `${org.industry} · ` : ''}{org.slug}
            </div>
          </div>
          <Link
            href={`/admin/control/accounts/${org.id}`}
            style={{ display: 'inline-flex', alignItems: 'center', gap: 6, color: '#7DD3FC', textDecoration: 'none', fontSize: 12.5, fontWeight: 700 }}
          >
            Open account detail <ExternalLink size={12} />
          </Link>
        </div>
      </SectionCard>

      {/* 2. Login Activity */}
      <SectionCard title="Login activity" icon={<LogIn size={16} style={{ color: '#86EFAC' }} />}>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, minmax(0,1fr))', gap: 12 }}>
          <MiniStat label="Total logins" value={String(login_activity.total_logins)} />
          <MiniStat label="Last 7 days"  value={String(login_activity.logins_last_7d)} />
          <MiniStat label="Last 30 days" value={String(login_activity.logins_last_30d)} />
          <MiniStat
            label="Last login"
            value={login_activity.last_login_at ? timeAgo(login_activity.last_login_at) : 'Never'}
            hint={login_activity.last_login_at ? fmtDate(login_activity.last_login_at) : ''}
          />
        </div>
        <p style={{ fontSize: 12, color: 'rgba(255,255,255,0.45)', margin: '10px 0 12px' }}>
          Login frequency (not time-in-app) — sourced from the login_events table.
        </p>
        {login_activity.recent.length > 0 && (
          <div style={{ marginTop: 6 }}>
            <div style={{ fontSize: 11, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.06em', color: 'rgba(255,255,255,0.5)', marginBottom: 8 }}>
              Recent (up to 20)
            </div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
              {login_activity.recent.map((l, i) => (
                <div key={i} style={{ padding: '6px 10px', fontSize: 12, color: 'rgba(255,255,255,0.75)', borderTop: i === 0 ? 'none' : `1px solid ${BORDER}` }}>
                  {fmtDateTime(l.occurred_at)}
                </div>
              ))}
            </div>
          </div>
        )}
      </SectionCard>

      {/* 3. Reports Generated by This User */}
      <SectionCard title="Reports generated by this user" icon={<FileText size={16} style={{ color: '#F0ABFC' }} />}>
        <p style={{ fontSize: 12, color: 'rgba(255,255,255,0.45)', margin: '0 0 12px' }}>
          Only reports written to <code style={{ background: 'rgba(255,255,255,0.06)', padding: '1px 5px', borderRadius: 3 }}>report_generation_log</code> carry per-user attribution.
          DCP Map and Insights Reports are tracked at the account level and are not shown here.
        </p>
        <ReportTypeRow name="Engagement Plan"        stats={reports_generated.by_type.engagement_plan} />
        <ReportTypeRow name="Future State Plan"      stats={reports_generated.by_type.future_state} />
        <ReportTypeRow name="ICP Calibration Report" stats={reports_generated.by_type.icp_calibration} />
        {reports_generated.recent.length > 0 && (
          <div style={{ marginTop: 16 }}>
            <div style={{ fontSize: 11, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.06em', color: 'rgba(255,255,255,0.5)', marginBottom: 8 }}>
              Recent (up to 20)
            </div>
            <div style={{ display: 'flex', flexDirection: 'column' }}>
              {reports_generated.recent.map((r, i) => (
                <div key={i} style={{ padding: '8px 10px', fontSize: 12.5, color: 'rgba(255,255,255,0.85)', borderTop: `1px solid ${BORDER}`, display: 'flex', justifyContent: 'space-between', gap: 12 }}>
                  <span style={{ fontWeight: 700 }}>{reportTypeLabel(r.report_type)}</span>
                  <span style={{ color: 'rgba(255,255,255,0.55)', fontSize: 11.5 }}>
                    {typeof r.metadata?.['trigger'] === 'string' && <span style={{ marginRight: 8 }}>{String(r.metadata['trigger'])}</span>}
                    {typeof r.metadata?.['format'] === 'string'  && <span style={{ marginRight: 8 }}>{String(r.metadata['format'])}</span>}
                    {fmtDateTime(r.generated_at)}
                  </span>
                </div>
              ))}
            </div>
          </div>
        )}
      </SectionCard>
    </div>
  )
}

// ─────────────────────────────────────────────────────────────────────────────
// Sub-components
// ─────────────────────────────────────────────────────────────────────────────
function SectionCard({ title, icon, children }: { title: string; icon: React.ReactNode; children: React.ReactNode }) {
  return (
    <div style={{ ...card, marginBottom: 14 }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 14 }}>
        {icon}
        <h3 style={{ fontSize: 12.5, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.06em', color: 'rgba(255,255,255,0.85)', margin: 0 }}>{title}</h3>
      </div>
      {children}
    </div>
  )
}

function ProfileField({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div>
      <div style={{ fontSize: 10.5, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.06em', color: 'rgba(255,255,255,0.5)' }}>{label}</div>
      <div style={{ fontSize: 14, marginTop: 4 }}>{children}</div>
    </div>
  )
}

function MiniStat({ label, value, hint }: { label: string; value: string; hint?: string }) {
  return (
    <div style={{ backgroundColor: 'rgba(255,255,255,0.02)', border: `1px solid ${BORDER}`, borderRadius: 8, padding: 12 }}>
      <div style={{ fontSize: 10.5, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.06em', color: 'rgba(255,255,255,0.5)' }}>{label}</div>
      <div style={{ fontSize: 18, fontWeight: 700, marginTop: 6 }}>{value}</div>
      {hint && <div style={{ fontSize: 10.5, color: 'rgba(255,255,255,0.4)', marginTop: 2 }}>{hint}</div>}
    </div>
  )
}

function ReportTypeRow({ name, stats }: { name: string; stats: { count: number; last_at: string | null } }) {
  const generated = stats.count > 0
  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: 12, padding: '10px 0', borderTop: `1px solid ${BORDER}` }}>
      {generated
        ? <CheckCircle2 size={16} style={{ color: '#86EFAC', flexShrink: 0 }} />
        : <Circle size={16} style={{ color: 'rgba(255,255,255,0.35)', flexShrink: 0 }} />}
      <div style={{ flex: 1, minWidth: 0 }}>
        <div style={{ fontSize: 13, fontWeight: 700, color: '#fff' }}>{name}</div>
        <div style={{ fontSize: 11.5, color: 'rgba(255,255,255,0.5)' }}>
          {generated
            ? <>{stats.count} generation{stats.count === 1 ? '' : 's'} · most recent {fmtDate(stats.last_at)}</>
            : <span style={{ color: 'rgba(255,255,255,0.4)' }}>Not generated by this user</span>}
        </div>
      </div>
    </div>
  )
}
