import { NextResponse } from 'next/server'
import { requireSuperAdmin } from '@/lib/auth/superAdmin'

export const runtime = 'nodejs'

// Response shape for the user detail page. Mirrors the shape of the account
// detail endpoint — profile + org + login activity + reports generated by
// this specific user. All read-only, all via the service client.
export interface AdminUserDetailResponse {
  user: {
    id: string
    email: string
    first_name: string | null
    last_name: string | null
    role: string
    is_active: boolean
    is_super_admin: boolean
    created_at: string
  }
  org: {
    id: string
    name: string
    slug: string
    status: string | null
    industry: string | null
    plan: string | null
  }
  login_activity: {
    total_logins: number
    last_login_at: string | null
    logins_last_7d: number
    logins_last_30d: number
    recent: Array<{ occurred_at: string }>
  }
  reports_generated: {
    total: number
    by_type: {
      engagement_plan: { count: number; last_at: string | null }
      future_state:    { count: number; last_at: string | null }
      icp_calibration: { count: number; last_at: string | null }
    }
    recent: Array<{ report_type: string; generated_at: string; metadata: Record<string, unknown> | null }>
  }
}

// GET /api/admin/users/[userId]/detail
// Super-admin gated read-only. Returns full profile + org + login history +
// per-user report-generation rollup for the specified user id.
export async function GET(
  _req: Request,
  ctx: { params: Promise<{ userId: string }> },
): Promise<NextResponse> {
  const auth = await requireSuperAdmin()
  if (!auth.ok) return auth.response
  const svc = auth.service

  const { userId } = await ctx.params
  if (!userId) return NextResponse.json({ error: 'userId is required' }, { status: 400 })

  // Confirm the user exists first — 404 cleanly on invalid id.
  const userRes = await svc
    .from('users')
    .select('id,org_id,email,first_name,last_name,role,is_active,is_super_admin,created_at')
    .eq('id', userId)
    .maybeSingle()
  if (userRes.error) return NextResponse.json({ error: userRes.error.message }, { status: 500 })
  if (!userRes.data) return NextResponse.json({ error: 'User not found' }, { status: 404 })

  type UserRow = {
    id: string; org_id: string; email: string;
    first_name: string | null; last_name: string | null;
    role: string; is_active: boolean; is_super_admin: boolean; created_at: string;
  }
  const user = userRes.data as UserRow

  // Everything else in parallel.
  const [orgRes, loginsRes, reportsRes] = await Promise.all([
    svc.from('organizations')
      .select('id,name,slug,status,industry,plan')
      .eq('id', user.org_id)
      .maybeSingle(),
    svc.from('login_events')
      .select('occurred_at')
      .eq('user_id', userId)
      .order('occurred_at', { ascending: false }),
    svc.from('report_generation_log')
      .select('report_type,generated_at,metadata')
      .eq('generated_by', userId)
      .order('generated_at', { ascending: false }),
  ])
  if (orgRes.error)     return NextResponse.json({ error: orgRes.error.message },     { status: 500 })
  if (loginsRes.error)  return NextResponse.json({ error: loginsRes.error.message },  { status: 500 })
  if (reportsRes.error) return NextResponse.json({ error: reportsRes.error.message }, { status: 500 })

  type OrgRow = { id: string; name: string; slug: string; status: string | null; industry: string | null; plan: string | null }
  type LoginRow = { occurred_at: string | null }
  type LogRow = { report_type: string; generated_at: string | null; metadata: unknown }

  const org = (orgRes.data as OrgRow | null) ?? {
    id: user.org_id, name: 'Unknown org', slug: '', status: null, industry: null, plan: null,
  }

  // ── Login activity ────────────────────────────────────────────────────────
  const logins = (loginsRes.data ?? []) as LoginRow[]
  const now = Date.now()
  const cut7d = now - 7 * 86_400_000
  const cut30d = now - 30 * 86_400_000
  let last: string | null = null
  let count7 = 0
  let count30 = 0
  for (const l of logins) {
    if (!l.occurred_at) continue
    if (!last || l.occurred_at > last) last = l.occurred_at
    const t = new Date(l.occurred_at).getTime()
    if (t >= cut7d)  count7++
    if (t >= cut30d) count30++
  }
  const recentLogins = logins
    .filter((l): l is { occurred_at: string } => typeof l.occurred_at === 'string')
    .slice(0, 20)
    .map(l => ({ occurred_at: l.occurred_at }))

  // ── Reports generated ─────────────────────────────────────────────────────
  const reports = (reportsRes.data ?? []) as LogRow[]
  const buckets = {
    engagement_plan: { count: 0, last_at: null as string | null },
    future_state:    { count: 0, last_at: null as string | null },
    icp_calibration: { count: 0, last_at: null as string | null },
  }
  for (const r of reports) {
    if (!r.generated_at) continue
    const bucket = (buckets as Record<string, { count: number; last_at: string | null }>)[r.report_type]
    if (!bucket) continue
    bucket.count++
    if (!bucket.last_at || r.generated_at > bucket.last_at) bucket.last_at = r.generated_at
  }
  const recentReports = reports
    .filter((r): r is { report_type: string; generated_at: string; metadata: unknown } => typeof r.generated_at === 'string')
    .slice(0, 20)
    .map(r => ({
      report_type: r.report_type,
      generated_at: r.generated_at,
      metadata: (r.metadata as Record<string, unknown> | null) ?? null,
    }))

  const payload: AdminUserDetailResponse = {
    user: {
      id: user.id,
      email: user.email,
      first_name: user.first_name,
      last_name: user.last_name,
      role: user.role,
      is_active: user.is_active,
      is_super_admin: user.is_super_admin,
      created_at: user.created_at,
    },
    org: {
      id: org.id, name: org.name, slug: org.slug, status: org.status,
      industry: org.industry, plan: org.plan,
    },
    login_activity: {
      total_logins: logins.length,
      last_login_at: last,
      logins_last_7d: count7,
      logins_last_30d: count30,
      recent: recentLogins,
    },
    reports_generated: {
      total: reports.length,
      by_type: buckets,
      recent: recentReports,
    },
  }

  return NextResponse.json(payload)
}
