'use client'

// In-app view of the ICP Calibration Report. Embeds the live PDF (generated by
// /api/icp/report) and offers PDF and Word downloads, matching how the other
// dashboard reports open in the application.

import { useState } from 'react'
import Link from 'next/link'
import { Loader2, Download, FileText, ArrowLeft } from 'lucide-react'

export default function IcpReportViewPage() {
  const [downloading, setDownloading] = useState<null | 'pdf' | 'docx'>(null)
  const [error, setError] = useState<string | null>(null)

  async function download(format: 'pdf' | 'docx') {
    if (downloading) return
    setDownloading(format)
    setError(null)
    try {
      const res = await fetch(format === 'docx' ? '/api/icp/report?format=docx' : '/api/icp/report', { method: 'GET' })
      if (!res.ok) {
        const body = await res.json().catch(() => ({})) as { error?: string }
        throw new Error(body.error ?? 'Could not generate the report.')
      }
      const blob = await res.blob()
      const url = URL.createObjectURL(blob)
      const cd = res.headers.get('Content-Disposition') ?? ''
      const match = /filename="([^"]+)"/.exec(cd)
      const a = document.createElement('a')
      a.href = url
      a.download = match ? match[1] : `ICP-Calibration-Report.${format}`
      document.body.appendChild(a)
      a.click()
      a.remove()
      URL.revokeObjectURL(url)
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Download failed. Please try again.')
    } finally {
      setDownloading(null)
    }
  }

  const primaryBtn: React.CSSProperties = {
    display: 'inline-flex', alignItems: 'center', gap: '8px', minHeight: '40px', padding: '0 18px',
    borderRadius: '8px', border: 'none', backgroundColor: '#0EA5E9', color: '#FFFFFF',
    fontSize: '13px', fontWeight: 600, fontFamily: 'inherit',
  }
  const secondaryBtn: React.CSSProperties = {
    ...primaryBtn,
    backgroundColor: 'rgba(255,255,255,0.08)', color: 'rgba(255,255,255,0.85)',
    border: '1px solid rgba(255,255,255,0.15)',
  }

  return (
    <div style={{ backgroundColor: '#0A1628', minHeight: '100vh', display: 'flex', flexDirection: 'column' }}>
      <header style={{ padding: '24px 32px', display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: '20px', flexWrap: 'wrap' }}>
        <div>
          <Link href="/dashboard" style={{
            display: 'inline-flex', alignItems: 'center', gap: '6px', fontSize: '12px', fontWeight: 600,
            color: 'rgba(255,255,255,0.5)', textDecoration: 'none', marginBottom: '10px',
          }}>
            <ArrowLeft size={14} /> Back to dashboard
          </Link>
          <h1 style={{ color: '#FFFFFF', fontSize: '22px', fontWeight: 700, margin: 0 }}>ICP Calibration Report</h1>
          <p style={{ color: 'rgba(255,255,255,0.55)', fontSize: '14px', margin: '6px 0 0', maxWidth: '640px', lineHeight: 1.55 }}>
            Your calibrated ideal customer profiles, the baseline beliefs and buyer evidence behind them, and an
            AI-tailored messaging and action-plan summary for each ICP. Reflects your latest data.
          </p>
        </div>
        <div style={{ display: 'flex', gap: '10px', alignItems: 'center', flexWrap: 'wrap' }}>
          <button onClick={() => void download('pdf')} disabled={downloading !== null}
            style={{ ...primaryBtn, cursor: downloading ? 'not-allowed' : 'pointer', backgroundColor: downloading === 'pdf' ? 'rgba(14,165,233,0.5)' : '#0EA5E9' }}>
            {downloading === 'pdf' ? <Loader2 size={15} className="animate-spin" /> : <Download size={15} />}
            Download PDF
          </button>
          <button onClick={() => void download('docx')} disabled={downloading !== null}
            style={{ ...secondaryBtn, cursor: downloading ? 'not-allowed' : 'pointer' }}>
            {downloading === 'docx' ? <Loader2 size={15} className="animate-spin" /> : <FileText size={15} />}
            Download Word
          </button>
          {error && <span style={{ fontSize: '12px', color: '#FCA5A5', maxWidth: '220px' }}>{error}</span>}
        </div>
      </header>

      <div style={{ flex: 1, padding: '0 32px 32px' }}>
        <div style={{
          backgroundColor: '#0F2140', border: '1px solid rgba(255,255,255,0.1)',
          borderRadius: '10px', overflow: 'hidden', height: 'calc(100vh - 190px)', minHeight: '480px',
        }}>
          <iframe
            src="/api/icp/report?inline=1"
            title="ICP Calibration Report"
            style={{ width: '100%', height: '100%', border: 'none', backgroundColor: '#FFFFFF' }}
          />
        </div>
      </div>
    </div>
  )
}
